version: '3.7'

services:

  dns:
    image: ichiky/dnsserv:1
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - network

  web:
    image: ichiky/webserv:2
    depends_on:
      - php
    deploy:
      replicas: 3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/pages:/var/www/html
    networks:
      - network

  php:
    image: ichiky/phpserv:1
    depends_on:
      - db
    deploy:
      replicas: 3
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${PHP_USER}
      MYSQL_PASSWORD: ${PHP_PASS}
      MYSQL_HOST: ${PHP_HOST}
    volumes:
      - ./web/pages:/var/www/html
    networks:
      - network
      - db

  db:
    image: mariadb
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: woodytoys
      MYSQL_USER: woodytoys
      MYSQL_PASSWORD: mypass
    volumes:
      - ./web/db/sql:/docker-entrypoint-initdb.d
      - ./web/db/conf/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    networks:
      - db

  mail:
    image: ichiky/mailserv:1
    hostname: mail.l2-10.ephec-ti.be
    deploy:
      replicas: 1
    env_file: ./mail/mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "465:465" 
      - "587:587"
      - "993:993"
    volumes:
      - ./mail/docker-data/dms/mail-data/:/var/mail/
      - ./mail/docker-data/dms/mail-state/:/var/mail-state/
      - ./mail/docker-data/dms/mail-logs/:/var/log/mail/
      - ./mail/docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    networks:
      - network
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

networks:
  network:
  db:
