services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./html/:/var/www/html/

  mariadb:
    image: mariadb:11.1
    env_file:
      - db/root.env
      - .env
    volumes:
      - ./db/sql/:/docker-entrypoint-initdb.d/  # MariaDB container automatically loads SQL script at startup
      - ./db/conf/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
  php:
    build: ./php
    volumes:
      - ./html/:/var/www/html/
    env_file:
      - .env